### ISSUE TITLE
Need a Bitbucker server support.

### ISSUE THREAD

**Issue by ronhks** [SonarSource/sonar-auth-bitbucket#21]
Right know the code only allows bitbucket cloud integration. 
The server version 8as I know) know, only supports API 1.0 which available at:

http://example.com/rest/api/1.0/

for example a rest method (GET)
http://example.com/rest/api/1.0/projects/{projectKey}/repos 

Could you integrate the bitbucket server with API 1.0?

**Comment by simonbrandhof** [comment]
Could you please clarify the versioning and the exact problem ? The plugin does support BitBucket Server (ex-Stash) and current version at Atlassian is 5.12, not 8.

**Comment by simonbrandhof** [comment]
In fact support of Bitbucket Server is already implemented (see #8) but it was not released yet. That is going to be done in the next few days. Meanwhile I close this ticket.
