### ISSUE TITLE
Need restriction on account domain

### ISSUE THREAD

**Issue by CyranoB** [SonarSource/sonar-auth-bitbucket#5]
Currently it seems that once the plugin is installed, anybody with a valid bitbucket account can log in. This is obviously an issue for corporate SonarQube installations.

We need a to restrict to a domain, e.g.:
user1@corporation.com -> authorized
user2@corporation.com -> authorized
user1@gmail.com -> not authorized
user2@gmail.com -> not authorized

Would this be doable?

**Comment by etki** [comment]
I anticipate this feature too, however, i think it would be better to add team restriction just as in github auth plugin.

**Comment by sintetico82** [comment]
We need also this feature here. When i realized that everyone can have access to our server i disabled the "Allow users to sign-up" feature. Is there an workaround?

**Comment by simonbrandhof** [comment]
GitHub issues are being moved to JIRA. Please drop a comment on https://jira.sonarsource.com/browse/AUTHBB-3 if you want to answer.
