### ISSUE TITLE
Invalid redirect_uri if sonar is running on yourURL.com/sonar

### ISSUE THREAD

**Issue by lopesdasilva** [SonarSource/sonar-auth-bitbucket#7]
Hi!,
I think you might have a problem  on your addon.
I have a installation of sonar that is running under /sonar/
When I click "Login with bitbucket" I'm redirect to the bitbucket page but I get the messaged:
Invalid redirect_uri
This integration is misconfigured. Contact the vendor for assistance.

I've already validated my secret and key.
I've notice that the redirect uri is this, and I think is not correct:
redirect_uri=https%3A%2F%2Fmysite%2Foauth2%2Fcallback%2Fbitbucket
and should be:
redirect_uri=https%3A%2F%2Fmysite%2Fsonar%2Foauth2%2Fcallback%2Fbitbucket

Thanks for your time

**Comment by julienlancelot** [comment]
Thanks for this feedback, this issue is on SonarQube side, it will be fixed in 6.3 version : https://jira.sonarsource.com/browse/SONAR-8413.

**Comment by simonbrandhof** [comment]
@julienlancelot this ticket can be closed as won't fix, correct ?

**Comment by julienlancelot** [comment]
@simonbrandhof yes, I'm closing it
